### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: models/Llama-3.2-1B-Instruct
adapter_name_or_path: saves/llama3.2-1b-lora-sft
template: llama3
trust_remote_code: true

### export
export_dir: output/llama3.2-1b-lora-sft
export_size: 5
export_device: cpu  # choices: [cpu, auto]
export_legacy_format: false
